"""
Shramsetu Automation Engine - Portal Reference Data

Static reference lists extracted directly from the real Shramsetu portal's
License FORM-25 page (Application_for_License_form_25_for_contractor.html):
the 88-item Nature of Work checkbox checklist and the 33-district Gujarat
checkbox list used for 'districts this license covers'. Each entry's `id`
matches the real portal checkbox value (natureOfWorkCheckbox_<id> /
districtCheckbox_<id>), so selections made here can be submitted straight
into the live portal via the webview auto-fill injector.
"""

NATURE_OF_WORK_OPTIONS = [
    {"id": 1, "label": "Allied services"},
    {"id": 2, "label": "Ambrodary Activities"},
    {"id": 3, "label": "Annual Maintenance Activities"},
    {"id": 4, "label": "Arc of LT Activities"},
    {"id": 5, "label": "Assemby Activities"},
    {"id": 6, "label": "Back And Support staff for local operation Activities"},
    {"id": 7, "label": "Back office Technical support"},
    {"id": 8, "label": "Building Maintenance  Activities"},
    {"id": 9, "label": "Cable laying Activities"},
    {"id": 10, "label": "Cafeteria Work"},
    {"id": 11, "label": "Canteen Services"},
    {"id": 12, "label": "CAPITAL OVERHAULING OF TURBINE & GENERATOR AND ITS AUXI."},
    {"id": 13, "label": "Carpentry Activities"},
    {"id": 14, "label": "Catering Work"},
    {"id": 15, "label": "Checking Activities"},
    {"id": 16, "label": "Civil Activities"},
    {"id": 17, "label": "Civil Maintenance Activities"},
    {"id": 18, "label": "Cleaning Activities"},
    {"id": 19, "label": "Cleaning of Equipments"},
    {"id": 20, "label": "Cloth Washing"},
    {"id": 21, "label": "Collection of waste"},
    {"id": 22, "label": "Commissioning Activities"},
    {"id": 23, "label": "Construction Activities"},
    {"id": 24, "label": "Cutting Activities"},
    {"id": 25, "label": "Data Entry Activities"},
    {"id": 26, "label": "Demolition Activities"},
    {"id": 27, "label": "Design Activities"},
    {"id": 28, "label": "Digging Work"},
    {"id": 29, "label": "Dismantle"},
    {"id": 30, "label": "Dispatch Work"},
    {"id": 31, "label": "Document Filling"},
    {"id": 32, "label": "Drawing & Sundry Job"},
    {"id": 33, "label": "Driving Activities"},
    {"id": 34, "label": "Electrical Activities"},
    {"id": 35, "label": "Electrical Maintenance Activities"},
    {"id": 36, "label": "Erection Activities"},
    {"id": 37, "label": "Excavation Work"},
    {"id": 38, "label": "Fabrication Activities"},
    {"id": 39, "label": "Fare Collection Work"},
    {"id": 40, "label": "Finishing Activities"},
    {"id": 41, "label": "Fire Fighting Activities"},
    {"id": 42, "label": "Folding Activities"},
    {"id": 43, "label": "Folding Activities"},
    {"id": 44, "label": "Forklift Driving"},
    {"id": 45, "label": "Gradening Activities"},
    {"id": 46, "label": "Housekeeping  Activities"},
    {"id": 47, "label": "HT/LT Activities"},
    {"id": 48, "label": "HVAC Activities"},
    {"id": 49, "label": "Hydraulic Assemble Work"},
    {"id": 51, "label": "Impelar Balancing"},
    {"id": 52, "label": "Inspection Activities"},
    {"id": 53, "label": "Installation Activities"},
    {"id": 54, "label": "Intigrated facility Services"},
    {"id": 55, "label": "Loading Activities"},
    {"id": 56, "label": "Logistic Service"},
    {"id": 57, "label": "Maintenance Activities"},
    {"id": 58, "label": "Material stacking"},
    {"id": 59, "label": "Mechanical Activities"},
    {"id": 60, "label": "Mechanical Maintenance  Activities"},
    {"id": 61, "label": "Movement and Shifting of Material, Tools, Equipment Activities"},
    {"id": 62, "label": "Network Cabling"},
    {"id": 63, "label": "Packing Activities"},
    {"id": 64, "label": "Painting Activities"},
    {"id": 65, "label": "Paramedical Service"},
    {"id": 66, "label": "Patient Care Services"},
    {"id": 67, "label": "PEB Erection"},
    {"id": 68, "label": "Pest Control Activities"},
    {"id": 69, "label": "Plumbing Activities"},
    {"id": 70, "label": "Prefabrication work"},
    {"id": 71, "label": "Printing Activities"},
    {"id": 72, "label": "Project Work"},
    {"id": 73, "label": "Refurbishment Work"},
    {"id": 74, "label": "Replacement Activities"},
    {"id": 75, "label": "Room Service"},
    {"id": 76, "label": "Scrap Handling"},
    {"id": 77, "label": "Security Activities"},
    {"id": 78, "label": "Shifting  Activities"},
    {"id": 79, "label": "Soldering Activities"},
    {"id": 80, "label": "Sorting"},
    {"id": 81, "label": "Structural Steel Work"},
    {"id": 82, "label": "Sweeping Activities"},
    {"id": 83, "label": "Testing Activities"},
    {"id": 84, "label": "Transportation"},
    {"id": 85, "label": "Unloading Activities"},
    {"id": 86, "label": "Washing of Equipments"},
    {"id": 87, "label": "Welding Activities"},
    {"id": 88, "label": "Wiring Activities"},
    {"id": 99, "label": "Other"},
]

GUJARAT_DISTRICT_OPTIONS = [
    {"id": 1, "label": "Ahmedabad"},
    {"id": 2, "label": "Amreli"},
    {"id": 3, "label": "Anand"},
    {"id": 4, "label": "Arvalli"},
    {"id": 5, "label": "Banas Kantha"},
    {"id": 6, "label": "Bharuch"},
    {"id": 7, "label": "Bhavnagar"},
    {"id": 8, "label": "Botad"},
    {"id": 9, "label": "Chhotaudepur"},
    {"id": 10, "label": "Dang"},
    {"id": 11, "label": "Devbhumi Dwarka"},
    {"id": 12, "label": "Dahod"},
    {"id": 13, "label": "Gandhinagar"},
    {"id": 14, "label": "Gir Somnath"},
    {"id": 15, "label": "Jamnagar"},
    {"id": 16, "label": "Junagadh"},
    {"id": 17, "label": "Kutch"},
    {"id": 18, "label": "Kheda"},
    {"id": 19, "label": "Mehsana"},
    {"id": 20, "label": "Mahisagar"},
    {"id": 21, "label": "Morbi"},
    {"id": 22, "label": "Narmada"},
    {"id": 23, "label": "Navsari"},
    {"id": 24, "label": "Panch Mahals"},
    {"id": 25, "label": "Patan"},
    {"id": 26, "label": "Porbandar"},
    {"id": 27, "label": "Rajkot"},
    {"id": 28, "label": "Sabar Kantha"},
    {"id": 29, "label": "Surat"},
    {"id": 30, "label": "Surendranagar"},
    {"id": 31, "label": "Tapi"},
    {"id": 32, "label": "Vadodara"},
    {"id": 33, "label": "Valsad"},
    {"id": 34, "label": "KALOL GANDHINAGAR"},
]
